name: Tag, Build, and Push Docker Image with Github Workflow

#Set up tagging/building only on tag releases
on:
  push:
    tags: [ staging-v* ]
    paths-ignore:
      - '**/README.md'

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_ACCESS_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: hmsccb/nhanes-workbench
        tags: type=match,pattern=staging-v(.*),group=1
        
    - name: Build, Tag, and Push to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Container/Dockerfile
        push: true
        tags: staging-version-${{ steps.meta.outputs.tags }}
        labels: staging-version-${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
