name: Tag, Build, and Push Docker Image with Github Workflow

#Set up tagging/building only on tag releases
on:
  push:
    tags: [ staging-v* ]
    paths-ignore:
      - '**/README.md'

jobs:
  build-container:
    name: Build container
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_ACCESS_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: tag version
      env: 
          TAG: "${{ steps.vars.outputs.tag }}"
      run: |
        TAG=${{ env.TAG }}
        TAG=${TAG/staging-v//staging-version-}
        echo TAG=${TAG} >> $GITHUB_ENV

    - name: Build, Tag, and Push to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Container/Dockerfile
        push: true
        tags: hmsccb/nhanes-workbench:latest, hmsccb/nhanes-workbench:${{ env.TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
